/*
  Project:   HZ-RR
  AUTOMATICALLY GENERATED CODE FROM PYTHON SCRIPT(s):
      "rr_autogene.py"
  */
// NOTE  !!! DO NOT CHANGE HERE !!! CHANGE IN PYTHON SCRIPT !!!


#include "rr.h"



void set_param_limits( void ) {
  // set parameter lower and upper limits
  // see definition of structure 'parameter_t' for explanation
  // NOTE   THIS PROGRAM WAS GENERATED BY 'parameter_generator01.py'
  // NOTE   MAKE CHANGES IN THE .py FILE - NOT HERE !!!
  // last generated: Mon Feb 20 20:39:48 2017

  // Minimaler Wert:            Maximaler Wert:
  pl[0].active        =     0; pl[1].active        =     1;
  pl[0].tvs           =  25.00; pl[1].tvs           =  45.00;
  pl[0].tvw           =  32.00; pl[1].tvw           =  45.00;
  pl[0].dts           =  20.00; pl[1].dts           = 3600.00;
  pl[0].dtw           =  20.00; pl[1].dtw           = 600.00;
  pl[0].dtS           =   2.00; pl[1].dtS           =  14.00;
  pl[0].dtSZu         =   0.00; pl[1].dtSZu         =  10.00;
  pl[0].dtWAuf        =   0.00; pl[1].dtWAuf        =  10.00;
  pl[0].dtInst        = 120.00; pl[1].dtInst        = 600.00;
  pl[0].tv0           =  35.00; pl[1].tv0           =  60.00;
  pl[0].tr0           =  30.00; pl[1].tr0           =  48.00;
  pl[0].tv1           =  65.00; pl[1].tv1           =  80.00;
  pl[0].tr1           =  45.00; pl[1].tr1           =  55.00;
  pl[0].dtLed         =   0.30; pl[1].dtLed         =   3.00;
  pl[0].ttol          =   0.50; pl[1].ttol          =   5.00;
  pl[0].pFZu          =   0.00; pl[1].pFZu          =   2.00;
  pl[0].pFAuf         =   0.00; pl[1].pFAuf         =   2.00;
  pl[0].dtMMn         =   0.10; pl[1].dtMMn         =   1.00;
  pl[0].dtMMx         =  20.00; pl[1].dtMMx         = 100.00;
  pl[0].IStop         =  30.00; pl[1].IStop         =  80.00;
  pl[0].IMn           =   3.00; pl[1].IMn           =  10.00;
  pl[0].dtVoc         =  20.00; pl[1].dtVoc         =  90.00;
  pl[0].vFix          =     0; pl[1].vFix          =     1;
  pl[0].test          =     0; pl[1].test          =     1;
  pl[0].fast          =     0; pl[1].fast          =   255;
  pl[0].tvzTValid     = 120.00; pl[1].tvzTValid     = 600.00;
}  // end of set_param_limits()



void param2default_valve( parameter_t* p ) {
  // v parameter set number e {0,1,2,3}
  // see definition of structure 'parameter_t' for explanation
  // NOTE   THIS PROGRAM WAS GENERATED BY 'parameter_generator01.py'
  // NOTE   MAKE CHANGES IN THE .py FILE - NOT HERE !!!
  // last generated: Mon Feb 20 20:39:48 2017

  strcpy( p->kenn, KENNUNG ); // Kennung; always in the first place
  p->active        =     1;
  p->tvs           =  30.00;
  p->tvw           =  35.00;
  p->dts           = 300.00;
  p->dtw           = 300.00;
  p->dtS           =   7.00;
  p->dtSZu         =   6.00;
  p->dtWAuf        =   4.00;
  p->dtInst        = 300.00;
  p->tv0           =  40.00;
  p->tr0           =  32.00;
  p->tv1           =  75.00;
  p->tr1           =  47.00;
  p->dtLed         =   1.00;
  p->ttol          =   2.50;
  p->pFZu          =   0.02;
  p->pFAuf         =   0.01;
  p->dtMMn         =   0.10;
  p->dtMMx         =  30.00;
  p->IStop         =  50.00;
  p->IMn           =   5.00;
  p->dtVoc         =  23.00;
  p->vFix          =     0;
  p->test          =     0;
  p->fast          =     0;
  p->tvzTValid     = 600.00;
  p->checksum      = 0xFEFEFEFE;    // will be calculated
}  // end of param2default()



int16_t parse_param( char *s0 ) {
  // parses string s0 containing a parameter set for one controller
  // return: fills in values in 
  // return: number of errors encountered while parsing
  // NOTE   THIS PROGRAM WAS GENERATED BY 'parameter_generator01.py'
  // NOTE   MAKE CHANGES IN THE .py FILE - NOT HERE !!!
  // last generated: Mon Feb 20 20:39:48 2017
  char        *cp;
  char        *errCheck;
  int16_t     err = 0;
  float       f;
  int32_t     ld;

  cp = strtok( s0, " " );  // Kennung
  if( cp == NULL ) err++;
  else {
  cp += 5;                 // jump over addr, command, controller nr.
    // check for proper kennung
    if(strcmp( cp, KENNUNG) != 0 ) err++;
    // >>> put later checks here for newer variants of protocol
  }

  cp = strtok( NULL, " " );   // active, should be "1" or "0"
  if( cp == NULL ) err++;
  else {
    parx.active = cp[0] - '0';
    if( parx.active > 1 ) {
      err++;
      parx.active = 1;
    }
  }

  cp = strtok( NULL, " " );   // tvs
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].tvs ) f = pl[0].tvs;
      if( f > pl[1].tvs ) f = pl[1].tvs;
      parx.tvs = f;
    }
  }

  cp = strtok( NULL, " " );   // tvw
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].tvw ) f = pl[0].tvw;
      if( f > pl[1].tvw ) f = pl[1].tvw;
      parx.tvw = f;
    }
  }

  cp = strtok( NULL, " " );   // dts
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].dts ) f = pl[0].dts;
      if( f > pl[1].dts ) f = pl[1].dts;
      parx.dts = f;
    }
  }

  cp = strtok( NULL, " " );   // dtw
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].dtw ) f = pl[0].dtw;
      if( f > pl[1].dtw ) f = pl[1].dtw;
      parx.dtw = f;
    }
  }

  cp = strtok( NULL, " " );   // dtS
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].dtS ) f = pl[0].dtS;
      if( f > pl[1].dtS ) f = pl[1].dtS;
      parx.dtS = f;
    }
  }

  cp = strtok( NULL, " " );   // dtSZu
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].dtSZu ) f = pl[0].dtSZu;
      if( f > pl[1].dtSZu ) f = pl[1].dtSZu;
      parx.dtSZu = f;
    }
  }

  cp = strtok( NULL, " " );   // dtWAuf
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].dtWAuf ) f = pl[0].dtWAuf;
      if( f > pl[1].dtWAuf ) f = pl[1].dtWAuf;
      parx.dtWAuf = f;
    }
  }

  cp = strtok( NULL, " " );   // dtInst
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].dtInst ) f = pl[0].dtInst;
      if( f > pl[1].dtInst ) f = pl[1].dtInst;
      parx.dtInst = f;
    }
  }

  cp = strtok( NULL, " " );   // tv0
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].tv0 ) f = pl[0].tv0;
      if( f > pl[1].tv0 ) f = pl[1].tv0;
      parx.tv0 = f;
    }
  }

  cp = strtok( NULL, " " );   // tr0
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].tr0 ) f = pl[0].tr0;
      if( f > pl[1].tr0 ) f = pl[1].tr0;
      parx.tr0 = f;
    }
  }

  cp = strtok( NULL, " " );   // tv1
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].tv1 ) f = pl[0].tv1;
      if( f > pl[1].tv1 ) f = pl[1].tv1;
      parx.tv1 = f;
    }
  }

  cp = strtok( NULL, " " );   // tr1
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].tr1 ) f = pl[0].tr1;
      if( f > pl[1].tr1 ) f = pl[1].tr1;
      parx.tr1 = f;
    }
  }

  cp = strtok( NULL, " " );   // dtLed
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].dtLed ) f = pl[0].dtLed;
      if( f > pl[1].dtLed ) f = pl[1].dtLed;
      parx.dtLed = f;
    }
  }

  cp = strtok( NULL, " " );   // ttol
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].ttol ) f = pl[0].ttol;
      if( f > pl[1].ttol ) f = pl[1].ttol;
      parx.ttol = f;
    }
  }

  cp = strtok( NULL, " " );   // pFZu
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].pFZu ) f = pl[0].pFZu;
      if( f > pl[1].pFZu ) f = pl[1].pFZu;
      parx.pFZu = f;
    }
  }

  cp = strtok( NULL, " " );   // pFAuf
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].pFAuf ) f = pl[0].pFAuf;
      if( f > pl[1].pFAuf ) f = pl[1].pFAuf;
      parx.pFAuf = f;
    }
  }

  cp = strtok( NULL, " " );   // dtMMn
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].dtMMn ) f = pl[0].dtMMn;
      if( f > pl[1].dtMMn ) f = pl[1].dtMMn;
      parx.dtMMn = f;
    }
  }

  cp = strtok( NULL, " " );   // dtMMx
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].dtMMx ) f = pl[0].dtMMx;
      if( f > pl[1].dtMMx ) f = pl[1].dtMMx;
      parx.dtMMx = f;
    }
  }

  cp = strtok( NULL, " " );   // IStop
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].IStop ) f = pl[0].IStop;
      if( f > pl[1].IStop ) f = pl[1].IStop;
      parx.IStop = f;
    }
  }

  cp = strtok( NULL, " " );   // IMn
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].IMn ) f = pl[0].IMn;
      if( f > pl[1].IMn ) f = pl[1].IMn;
      parx.IMn = f;
    }
  }

  cp = strtok( NULL, " " );   // dtVoc
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].dtVoc ) f = pl[0].dtVoc;
      if( f > pl[1].dtVoc ) f = pl[1].dtVoc;
      parx.dtVoc = f;
    }
  }

  cp = strtok( NULL, " " );   // vFix
  if( cp == 0 ) err++;
  if( !err ) {
    ld = strtol( cp, &errCheck, 10 );
    if( errCheck == cp ) err++;
    else {
      if( ld < pl[0].vFix ) ld = pl[0].vFix;
      if( ld > pl[1].vFix ) ld = pl[1].vFix;
      parx.vFix = ld;
    }
  }

  cp = strtok( NULL, " " );   // test
  if( cp == 0 ) err++;
  if( !err ) {
    ld = strtol( cp, &errCheck, 10 );
    if( errCheck == cp ) err++;
    else {
      if( ld < pl[0].test ) ld = pl[0].test;
      if( ld > pl[1].test ) ld = pl[1].test;
      parx.test = ld;
    }
  }

  cp = strtok( NULL, " " );   // fast
  if( cp == 0 ) err++;
  if( !err ) {
    ld = strtol( cp, &errCheck, 10 );
    if( errCheck == cp ) err++;
    else {
      if( ld < pl[0].fast ) ld = pl[0].fast;
      if( ld > pl[1].fast ) ld = pl[1].fast;
      parx.fast = ld;
    }
  }

  cp = strtok( NULL, " " );   // tvzTValid
  if( cp == 0 ) err++;
  if( !err ) {
    f = strtod( cp, &errCheck );
    if( errCheck == cp ) err++;
    else {
      if( f < pl[0].tvzTValid ) f = pl[0].tvzTValid;
      if( f > pl[1].tvzTValid ) f = pl[1].tvzTValid;
      parx.tvzTValid = f;
    }
  }

  return err;
}  // end of parse_param()



void param_var_string( char *s ) {
  // returns string with variable names of a controller parameter-set 
  // NOTE   THIS PROGRAM WAS GENERATED BY 'parameter_generator01.py'
  // NOTE   MAKE CHANGES IN THE .py FILE - NOT HERE !!!
  // last generated: Mon Feb 20 20:39:48 2017
  strcpy( s, 
    "kenn active tvs tvw "
    "dts dtw dtS dtSZu "
    "dtWAuf dtInst tv0 tr0 "
    "tv1 tr1 dtLed ttol "
    "pFZu pFAuf dtMMn dtMMx "
    "IStop IMn dtVoc vFix "
    "test fast tvzTValid" );
}  // end of param_var_string()



void param_var_values( char *s1) {
  // parameters for controllers as currently used
  uint8_t      v = com.con - 1;
  parameter_t *p = &par[v];
  char fs[]= {
    "%s %d "
    "%5.1f %5.1f %5.1f %5.1f "
    "%5.1f %5.1f %5.1f %5.1f "
    "%5.1f %5.1f %5.1f %5.1f "
    "%5.1f %5.1f %5.2f %5.2f "
    "%5.1f %5.1f %5.1f %5.1f "
    "%5.1f %d %d %d "
    "%5.1f" 
  };
  snprintf( s1, TX_CMD_SIZE, fs, \
    p->kenn  ,p->active,\
    p->tvs   ,p->tvw   ,p->dts   ,p->dtw   ,\
    p->dtS   ,p->dtSZu ,p->dtWAuf,p->dtInst,\
    p->tv0   ,p->tr0   ,p->tv1   ,p->tr1   ,\
    p->dtLed ,p->ttol  ,p->pFZu  ,p->pFAuf ,\
    p->dtMMn ,p->dtMMx ,p->IStop ,p->IMn   ,\
    p->dtVoc ,p->vFix  ,p->test  ,p->fast  ,\
    p->tvzTValid
  );
}
